# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('month', models.CharField(max_length=7)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('total_budget_amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category_id', models.UUIDField()),
                ('budget_amount', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['owner', 'month'], name='budget_budg_owner_i_dc0afe_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['owner', 'budget'], name='budget_budg_owner_i_3c7eff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetcategory',
            unique_together={('budget', 'category_id')},
        ),
    ]
