# Generated by Django 5.2.12 on 2026-04-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('register', 'Registration Verification'), ('login', 'Login Verification'), ('change_password', 'Password Change Verification'), ('forgot_password', 'Forgot Password Verification')], db_index=True, max_length=20),
        ),
    ]
