# Generated by Django 5.2.12 on 2026-04-21 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
