# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('life', 'Life'), ('health', 'Health'), ('vehicle', 'Vehicle'), ('property', 'Property'), ('travel', 'Travel'), ('critical_illness', 'Critical Illness'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(max_length=255)),
                ('policy_number', models.CharField(max_length=255)),
                ('group_policy_number', models.CharField(blank=True, default='', max_length=255)),
                ('coverage_amount', models.BigIntegerField(default=0)),
                ('premium_amount', models.BigIntegerField(default=0)),
                ('premium_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannually', 'Semiannually'), ('annually', 'Annually'), ('single', 'Single')], default='monthly', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('next_premium_due_date', models.DateField(blank=True, null=True)),
                ('total_premium_paid', models.BigIntegerField(default=0)),
                ('paid_premiums_count', models.IntegerField(default=0)),
                ('total_claimed_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('claimed', 'Claimed'), ('lapsed', 'Lapsed'), ('pending_renewal', 'Pending Renewal')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('policy_term', models.IntegerField(blank=True, null=True)),
                ('maturity_benefit', models.BigIntegerField(default=0)),
                ('rider_names', models.JSONField(blank=True, default=list)),
                ('deductible_amount', models.BigIntegerField(default=0)),
                ('copay_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('network_hospitals', models.CharField(blank=True, default='', max_length=500)),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('truck', 'Truck'), ('other', 'Other')], max_length=20, null=True)),
                ('vehicle_registration', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=255)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=20, null=True)),
                ('property_address', models.TextField(blank=True, default='')),
                ('property_value', models.BigIntegerField(default=0)),
                ('bank_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20)),
                ('percentage', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='insurance.insurance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Beneficiary',
                'verbose_name_plural': 'Insurance Beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_number', models.CharField(blank=True, default='', max_length=255)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('claim_amount', models.BigIntegerField(default=0)),
                ('approved_amount', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('in_review', 'In Review')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('documents', models.TextField(blank=True, default='')),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Claim',
                'verbose_name_plural': 'Insurance Claims',
                'ordering': ['-claim_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePremiumPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_number', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('bank_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_payments', to='insurance.insurance')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insurance Premium Payment',
                'verbose_name_plural': 'Insurance Premium Payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
