# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('tax_return', 'Tax Return'), ('insurance_policy', 'Insurance Policy'), ('property_deed', 'Property Deed'), ('bank_statement', 'Bank Statement'), ('investment_statement', 'Investment Statement'), ('loan_document', 'Loan Document'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('invoice', 'Invoice'), ('id_proof', 'ID Proof'), ('medical_record', 'Medical Record'), ('education_certificate', 'Education Certificate'), ('vehicle_registration', 'Vehicle Registration'), ('other', 'Other')], default='other', max_length=30)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('jpg', 'JPG'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('csv', 'CSV'), ('txt', 'TXT'), ('zip', 'ZIP'), ('other', 'Other')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('folder_id', models.CharField(blank=True, default='', max_length=36)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('reminder_before_days', models.IntegerField(blank=True, null=True)),
                ('linked_entity_id', models.CharField(blank=True, default='', max_length=36)),
                ('linked_entity_type', models.CharField(blank=True, choices=[('insurance', 'Insurance'), ('loan', 'Loan'), ('mortgage', 'Mortgage'), ('asset', 'Asset'), ('investment', 'Investment'), ('lending', 'Lending'), ('invoice', 'Invoice'), ('other', 'Other')], default='', max_length=50)),
                ('current_version', models.IntegerField(default=1)),
                ('shared_with', models.CharField(blank=True, default='', max_length=255)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Vault Item',
                'verbose_name_plural': 'Document Vault Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document.documentvaultitem')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
