# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('rent', 'Rent'), ('utilities', 'Utilities'), ('subscriptions', 'Subscriptions'), ('loan_emi', 'Loan EMI'), ('insurance_premium', 'Insurance Premium'), ('credit_card', 'Credit Card'), ('medical', 'Medical'), ('education', 'Education'), ('vehicle', 'Vehicle'), ('service_contract', 'Service Contract'), ('tax', 'Tax'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('paid', 'Paid'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('payee_name', models.CharField(max_length=255)),
                ('payee_account', models.CharField(blank=True, default='', max_length=255)),
                ('payee_website', models.URLField(blank=True, default='')),
                ('due_date', models.DateField()),
                ('due_date_day_of_month', models.IntegerField(blank=True, null=True)),
                ('grace_period_days', models.IntegerField(blank=True, null=True)),
                ('late_fee_amount', models.BigIntegerField(blank=True, null=True)),
                ('late_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannually', 'Semiannually'), ('annually', 'Annually')], default='none', max_length=20)),
                ('recurrence_day_of_month', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('auto_pay_enabled', models.BooleanField(default=False)),
                ('auto_pay_method', models.CharField(blank=True, default='', max_length=100)),
                ('auto_pay_day_before', models.IntegerField(blank=True, null=True)),
                ('total_paid_amount', models.BigIntegerField(default=0)),
                ('total_payments_count', models.IntegerField(default=0)),
                ('last_paid_date', models.DateField(blank=True, null=True)),
                ('last_paid_amount', models.BigIntegerField(blank=True, null=True)),
                ('reminder_days_before', models.IntegerField(default=3)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('linked_entity_id', models.UUIDField(blank=True, null=True)),
                ('linked_entity_type', models.CharField(blank=True, choices=[('loan', 'Loan'), ('mortgage', 'Mortgage'), ('insurance', 'Insurance'), ('investment', 'Investment'), ('card', 'Card'), ('invoice', 'Invoice'), ('calendar', 'Calendar'), ('other', 'Other')], max_length=50, null=True)),
                ('linked_calendar_event_id', models.UUIDField(blank=True, null=True)),
                ('preferred_payment_account_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillPaymentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('payment_method', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history_set', to='bill.bill')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
