# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('emi_payment', 'EMI Payment'), ('insurance_premium', 'Insurance Premium'), ('bill_payment', 'Bill Payment'), ('investment_maturity', 'Investment Maturity'), ('investment_deposit', 'Investment Deposit'), ('dividend', 'Dividend'), ('tax_deadline', 'Tax Deadline'), ('salary', 'Salary'), ('rental_income', 'Rental Income'), ('rental_payment', 'Rental Payment'), ('lending_payment', 'Lending Payment'), ('subscription', 'Subscription'), ('maintenance', 'Maintenance'), ('document_renewal', 'Document Renewal'), ('milestone', 'Milestone'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='BDT', max_length=10)),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('recurrence', models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannually', 'Semiannually'), ('annually', 'Annually'), ('custom', 'Custom')], default='none', max_length=20)),
                ('custom_recurrence_days', models.IntegerField(blank=True, null=True)),
                ('recurrence_day_of_month', models.IntegerField(blank=True, null=True)),
                ('next_occurrence_date', models.DateField(blank=True, null=True)),
                ('reminder_days_before', models.IntegerField(default=0)),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('second_reminder_days_before', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('linked_entity_id', models.UUIDField(blank=True, null=True)),
                ('linked_entity_type', models.CharField(blank=True, choices=[('loan', 'Loan'), ('mortgage', 'Mortgage'), ('insurance', 'Insurance'), ('investment', 'Investment'), ('lending', 'Lending'), ('invoice', 'Invoice'), ('document', 'Document'), ('card', 'Card'), ('bill', 'Bill'), ('other', 'Other')], max_length=50, null=True)),
                ('linked_bill_id', models.UUIDField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', '-created_at'],
            },
        ),
    ]
