# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('auto', 'Auto'), ('education', 'Education'), ('business', 'Business'), ('other', 'Other')], max_length=50)),
                ('lender_name', models.CharField(max_length=255)),
                ('principal_amount', models.BigIntegerField(default=0)),
                ('current_balance', models.BigIntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('emi_amount', models.BigIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('next_payment_amount', models.BigIntegerField(default=0)),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('paid_installments', models.IntegerField(default=0)),
                ('total_installments', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='active', max_length=50)),
                ('bank_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('principal_component', models.BigIntegerField(default=0)),
                ('interest_component', models.BigIntegerField(default=0)),
                ('payment_date', models.DateField()),
                ('payment_number', models.IntegerField()),
                ('bank_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loan.loan')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Payment',
                'verbose_name_plural': 'Loan Payments',
                'ordering': ['payment_number'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['owner', 'status'], name='loan_loan_owner_i_b600da_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['owner', 'type'], name='loan_loan_owner_i_5b18a6_idx'),
        ),
        migrations.AddIndex(
            model_name='loanpayment',
            index=models.Index(fields=['owner', 'loan'], name='loan_loanpa_owner_i_dd5004_idx'),
        ),
    ]
