# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicle', 'Vehicle'), ('electronics', 'Electronics'), ('furniture', 'Furniture'), ('jewelry', 'Jewelry'), ('art', 'Art'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.BigIntegerField()),
                ('purchase_from', models.CharField(blank=True, default='', max_length=255)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('current_value', models.BigIntegerField()),
                ('current_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], max_length=20)),
                ('location', models.TextField(blank=True, default='')),
                ('depreciation_method', models.CharField(choices=[('none', 'None'), ('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='none', max_length=20)),
                ('useful_life_years', models.IntegerField(blank=True, null=True)),
                ('salvage_value', models.BigIntegerField(blank=True, null=True)),
                ('current_book_value', models.BigIntegerField(blank=True, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial'), ('condo', 'Condo'), ('plot', 'Plot')], max_length=30, null=True)),
                ('property_address', models.TextField(blank=True, default='')),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('floor_number', models.CharField(blank=True, default='', max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, default='', max_length=255)),
                ('khatian_number', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('truck', 'Truck'), ('bicycle', 'Bicycle'), ('rickshaw_van', 'Rickshaw Van'), ('other', 'Other')], max_length=30, null=True)),
                ('vehicle_brand', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_registration_no', models.CharField(blank=True, default='', max_length=255)),
                ('engine_no', models.CharField(blank=True, default='', max_length=255)),
                ('chassis_no', models.CharField(blank=True, default='', max_length=255)),
                ('mileage_km', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=255)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('necklace', 'Necklace'), ('ring', 'Ring'), ('earring', 'Earring'), ('bangle', 'Bangle'), ('bracelet', 'Bracelet'), ('chain', 'Chain'), ('pendant', 'Pendant'), ('watch', 'Watch'), ('set', 'Set'), ('other', 'Other')], max_length=30, null=True)),
                ('material', models.CharField(blank=True, default='', max_length=100)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purity', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('leased', 'Leased'), ('sold', 'Sold'), ('gifted', 'Gifted'), ('damaged', 'Damaged'), ('disposed', 'Disposed')], default='owned', max_length=20)),
                ('ownership_percentage', models.IntegerField(default=100)),
                ('loan_against_asset', models.BooleanField(default=False)),
                ('insurance_policy_id', models.UUIDField(blank=True, null=True)),
                ('co_owners', models.CharField(blank=True, default='', max_length=255)),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.BigIntegerField()),
                ('note', models.TextField(blank=True, default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_set', to='asset.asset')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
