import type { Budget } from '../types';

export const mockBudgets: Budget[] = [
  {
    id: 'budget_001',
    name: 'April 2026 Budget',
    month: '2026-04',
    currency: 'BDT',
    totalBudgetAmount: 120000,
    allocatedAmount: 115000,
    availableBalance: 5000,
    remainingBalance: 18400,
    isOverBudget: false,
    overAmount: 0,
    forecastedSpend: 125000,
    forecastGap: 5000,
    dailySafeSpend: 1538,
    requiredDailyReduction: 365,
    requiredExtraIncome: 7300,
    // NOTE: spentAmount is derived from actual Expense records (via categoryId).
    // The BudgetTransaction arrays were removed to eliminate data duplication.
    // Budget spending is computed at query time from expenseStore.
    categories: [
      {
        id: 'bc_001',
        name: 'Rent/Housing',
        categoryId: 'cat_004',
        budgetAmount: 30000,
        allocatedAmount: 30000,
        availableBalance: 0,
        remainingBalance: 5000,
        spentAmount: 25000,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 30000,
        dailySafeSpend: 0,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_002',
        name: 'Food & Groceries',
        categoryId: 'cat_001',
        budgetAmount: 25000,
        allocatedAmount: 22000,
        availableBalance: 3000,
        remainingBalance: 9000,
        spentAmount: 13000,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 27000,
        dailySafeSpend: 750,
        requiredDailyReduction: 150,
        requiredExtraIncome: 3000,
      },
      {
        id: 'bc_003',
        name: 'Transport',
        categoryId: 'cat_002',
        budgetAmount: 10000,
        allocatedAmount: 8000,
        availableBalance: 2000,
        remainingBalance: 5800,
        spentAmount: 2200,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 8000,
        dailySafeSpend: 483,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_004',
        name: 'Shopping',
        categoryId: 'cat_007',
        budgetAmount: 15000,
        allocatedAmount: 15000,
        availableBalance: 0,
        remainingBalance: -3900,
        spentAmount: 18900,
        isOverBudget: true,
        overAmount: 3900,
        forecastedSpend: 22000,
        dailySafeSpend: 0,
        requiredDailyReduction: 975,
        requiredExtraIncome: 4875,
      },
      {
        id: 'bc_005',
        name: 'Utilities & Subscriptions',
        categoryId: 'cat_003',
        budgetAmount: 11000,
        allocatedAmount: 10000,
        availableBalance: 1000,
        remainingBalance: 5300,
        spentAmount: 5700,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 10500,
        dailySafeSpend: 442,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_006',
        name: 'Dining Out & Entertainment',
        categoryId: 'cat_009',
        budgetAmount: 18000,
        allocatedAmount: 15000,
        availableBalance: 3000,
        remainingBalance: 11700,
        spentAmount: 6300,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 16000,
        dailySafeSpend: 978,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
    ],
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-04-19T12:00:00.000Z',
  },
  {
    id: 'budget_002',
    name: 'May 2026 Budget',
    month: '2026-05',
    currency: 'BDT',
    totalBudgetAmount: 130000,
    allocatedAmount: 95000,
    availableBalance: 35000,
    remainingBalance: 130000,
    isOverBudget: false,
    overAmount: 0,
    forecastedSpend: 128000,
    forecastGap: 0,
    dailySafeSpend: 4194,
    requiredDailyReduction: 0,
    requiredExtraIncome: 0,
    categories: [
      {
        id: 'bc_007',
        name: 'Rent/Housing',
        categoryId: 'cat_004',
        budgetAmount: 30000,
        allocatedAmount: 30000,
        availableBalance: 0,
        remainingBalance: 30000,
        spentAmount: 0,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 30000,
        dailySafeSpend: 968,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_008',
        name: 'Food & Groceries',
        categoryId: 'cat_001',
        budgetAmount: 25000,
        allocatedAmount: 25000,
        availableBalance: 0,
        remainingBalance: 25000,
        spentAmount: 0,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 23000,
        dailySafeSpend: 806,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_009',
        name: 'Transport',
        categoryId: 'cat_002',
        budgetAmount: 10000,
        allocatedAmount: 8000,
        availableBalance: 2000,
        remainingBalance: 10000,
        spentAmount: 0,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 9000,
        dailySafeSpend: 323,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_010',
        name: 'Shopping',
        categoryId: 'cat_007',
        budgetAmount: 15000,
        allocatedAmount: 12000,
        availableBalance: 3000,
        remainingBalance: 15000,
        spentAmount: 0,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 14000,
        dailySafeSpend: 452,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_011',
        name: 'Utilities & Subscriptions',
        categoryId: 'cat_003',
        budgetAmount: 11000,
        allocatedAmount: 10000,
        availableBalance: 1000,
        remainingBalance: 11000,
        spentAmount: 0,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 10500,
        dailySafeSpend: 339,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
      {
        id: 'bc_012',
        name: 'Dining Out & Entertainment',
        categoryId: 'cat_009',
        budgetAmount: 18000,
        allocatedAmount: 10000,
        availableBalance: 8000,
        remainingBalance: 18000,
        spentAmount: 0,
        isOverBudget: false,
        overAmount: 0,
        forecastedSpend: 17000,
        dailySafeSpend: 548,
        requiredDailyReduction: 0,
        requiredExtraIncome: 0,
      },
    ],
    createdAt: '2026-04-20T00:00:00.000Z',
    updatedAt: '2026-04-20T00:00:00.000Z',
  },
];
