import type { CalendarEvent } from '../types';

export const mockCalendarEvents: CalendarEvent[] = [
  // ==================== Salary & Income (NOT duplicated by bills) ====================
  {
    id: 'cal_011',
    title: 'Monthly Salary — SoftwareBangladesh',
    description: 'Monthly salary credit from SoftwareBangladesh Ltd.',
    category: 'salary',
    status: 'upcoming',
    amount: 185000,
    currency: 'BDT',
    eventDate: '2026-05-28T00:00:00.000Z',
    recurrence: 'monthly',
    recurrenceDayOfMonth: 28,
    reminderDaysBefore: 0,
    reminderEnabled: false,
    color: '#22c55e',
    priority: 'high',
    notes: 'Position: Senior Software Engineer. Credited to City Bank salary account.',
    tags: ['income', 'salary', 'monthly', 'employment'],
  },
  {
    id: 'cal_012',
    title: 'Office Rent Received — TechNova',
    description: 'Monthly rent from Gulshan office commercial space tenant.',
    category: 'rental_income',
    status: 'upcoming',
    amount: 85000,
    currency: 'BDT',
    eventDate: '2026-05-01T00:00:00.000Z',
    recurrence: 'monthly',
    recurrenceDayOfMonth: 1,
    reminderDaysBefore: 0,
    reminderEnabled: false,
    color: '#22c55e',
    linkedEntityId: 'ast_002',
    linkedEntityType: 'asset',
    priority: 'medium',
    notes: 'Tenant: TechNova Solutions Ltd. Rent: ৳85,000/month. Credited to DBBL savings.',
    tags: ['income', 'rental', 'commercial', 'monthly'],
  },

  // ==================== Investment Events (NOT duplicated by bills) ====================
  {
    id: 'cal_013',
    title: 'IDLC DPS Monthly Deposit',
    description: 'Monthly DPS deposit to IDLC Finance. ৳25,000/month.',
    category: 'investment_deposit',
    status: 'upcoming',
    amount: 25000,
    currency: 'BDT',
    eventDate: '2026-05-15T00:00:00.000Z',
    recurrence: 'monthly',
    recurrenceDayOfMonth: 15,
    endDate: '2026-12-15T23:59:59.000Z',
    reminderDaysBefore: 3,
    reminderEnabled: true,
    color: '#3b82f6',
    linkedEntityId: 'inv_002',
    linkedEntityType: 'investment',
    priority: 'medium',
    notes: 'DPS account at IDLC. 24 deposits done. 8 remaining. Maturity: Dec 2026.',
    tags: ['investment', 'dps', 'idlc', 'monthly'],
  },
  {
    id: 'cal_014',
    title: 'Sanchaypatra WEDB Maturity',
    description: 'Wage Earners Development Bond matures. Redeem or reinvest.',
    category: 'investment_maturity',
    status: 'upcoming',
    amount: 1000000,
    currency: 'BDT',
    eventDate: '2028-06-14T00:00:00.000Z',
    recurrence: 'none',
    reminderDaysBefore: 60,
    reminderEnabled: true,
    secondReminderDaysBefore: 30,
    color: '#3b82f6',
    linkedEntityId: 'inv_003',
    linkedEntityType: 'investment',
    priority: 'high',
    notes: 'Bond value: ৳10,00,000. Interest: 11.03% tax-free. Decide: redeem or reinvest.',
    tags: ['investment', 'sanchaypatra', 'wedb', 'maturity', 'bangladesh-bank'],
  },
  {
    id: 'cal_015',
    title: 'DBBL FDR Interest Credit',
    description: 'Quarterly interest credit from DBBL Fixed Deposit.',
    category: 'dividend',
    status: 'upcoming',
    amount: 18750,
    currency: 'BDT',
    eventDate: '2026-06-30T00:00:00.000Z',
    recurrence: 'quarterly',
    reminderDaysBefore: 3,
    reminderEnabled: false,
    color: '#22c55e',
    linkedEntityId: 'inv_001',
    linkedEntityType: 'investment',
    priority: 'low',
    notes: 'FDR: ৳5,00,000 at 7.5% quarterly compounding. Quarterly interest: ~৳18,750.',
    tags: ['investment', 'fdr', 'dbbl', 'interest', 'quarterly'],
  },

  // ==================== Tax Deadlines (NOT duplicated by bills) ====================
  {
    id: 'cal_016',
    title: 'Income Tax Return Filing (FY 2025-26)',
    description: 'Last date for individual income tax return submission to NBR. Assessment year 2025-26.',
    category: 'tax_deadline',
    status: 'upcoming',
    eventDate: '2026-11-30T23:59:59.000Z',
    recurrence: 'annually',
    reminderDaysBefore: 90,
    reminderEnabled: true,
    secondReminderDaysBefore: 30,
    color: '#dc2626',
    priority: 'high',
    notes: 'NBR online portal. Tax reference: 450821-Dhaka-36. Gather all documents by October.',
    tags: ['tax', 'income-tax', 'nbr', 'deadline', 'annual'],
  },

  // ==================== Lending Payment (NOT duplicated by bills) ====================
  {
    id: 'cal_018',
    title: 'Repayment from Kamal — Monthly',
    description: 'Monthly repayment from brother Kamal for personal loan.',
    category: 'lending_payment',
    status: 'upcoming',
    amount: 15000,
    currency: 'BDT',
    eventDate: '2026-05-10T00:00:00.000Z',
    recurrence: 'monthly',
    recurrenceDayOfMonth: 10,
    endDate: '2027-06-10T23:59:59.000Z',
    reminderDaysBefore: 2,
    reminderEnabled: true,
    color: '#06b6d4',
    linkedEntityId: 'lend_002',
    linkedEntityType: 'lending',
    priority: 'medium',
    notes: 'Principal + interest. 13 installments remaining.',
    tags: ['lending', 'repayment', 'family', 'monthly'],
  },

  // ==================== Maintenance (NOT duplicated by bills) ====================
  {
    id: 'cal_020',
    title: 'AC Service — Daikin (2 units)',
    description: 'Biannual AC servicing for Daikin inverter units.',
    category: 'maintenance',
    status: 'upcoming',
    amount: 3000,
    currency: 'BDT',
    eventDate: '2026-10-10T00:00:00.000Z',
    recurrence: 'none',
    reminderDaysBefore: 7,
    reminderEnabled: true,
    color: '#f97316',
    priority: 'low',
    notes: '2 units at home. Next service: Oct 2026. Last: Apr 2026.',
    tags: ['maintenance', 'ac', 'daikin', 'home'],
  },

  // ==================== Document Renewals (NOT duplicated by bills) ====================
  {
    id: 'cal_021',
    title: 'Employment Contract Renewal',
    description: 'Current employment contract with SoftwareBangladesh expires. Needs renewal discussion.',
    category: 'document_renewal',
    status: 'upcoming',
    eventDate: '2027-02-28T23:59:59.000Z',
    recurrence: 'none',
    reminderDaysBefore: 90,
    reminderEnabled: true,
    secondReminderDaysBefore: 30,
    color: '#8b5cf6',
    linkedEntityId: 'doc_015',
    linkedEntityType: 'document',
    priority: 'high',
    notes: 'Contract ends Feb 2027. Schedule review meeting with manager by Dec 2026.',
    tags: ['contract', 'employment', 'renewal'],
  },

  // ==================== Milestones (NOT duplicated by bills) ====================
  {
    id: 'cal_022',
    title: 'IDLC DPS Maturity',
    description: 'IDLC DPS account matures. Total maturity amount: ~৳6,30,000.',
    category: 'milestone',
    status: 'upcoming',
    amount: 630000,
    currency: 'BDT',
    eventDate: '2026-12-15T00:00:00.000Z',
    recurrence: 'none',
    reminderDaysBefore: 60,
    reminderEnabled: true,
    color: '#0ea5e9',
    linkedEntityId: 'inv_002',
    linkedEntityType: 'investment',
    priority: 'high',
    notes: '24 x ৳25,000 = ৳6,00,000 deposits + ৳30,000 interest. Plan for reinvestment.',
    tags: ['milestone', 'dps', 'maturity', 'idlc'],
  },
  {
    id: 'cal_023',
    title: 'Rental Agreement Renewal — Gulshan Office',
    description: 'Annual commercial rental agreement renewal for Gulshan office.',
    category: 'document_renewal',
    status: 'upcoming',
    amount: 85000,
    currency: 'BDT',
    eventDate: '2027-01-01T00:00:00.000Z',
    recurrence: 'annually',
    reminderDaysBefore: 60,
    reminderEnabled: true,
    secondReminderDaysBefore: 30,
    color: '#8b5cf6',
    linkedEntityId: 'doc_014',
    linkedEntityType: 'document',
    priority: 'medium',
    notes: 'Review rent increase clause. Current: ৳85,000/month. Consider 10% hike.',
    tags: ['contract', 'rental', 'commercial', 'renewal'],
  },

  // ==================== Insurance (no bill equivalent) ====================
  {
    id: 'cal_006',
    title: 'Pioneer Motor Insurance Renewal',
    description: 'Annual comprehensive motor insurance for Toyota Corolla X.',
    category: 'insurance_premium',
    status: 'upcoming',
    amount: 32500,
    currency: 'BDT',
    eventDate: '2027-04-10T00:00:00.000Z',
    recurrence: 'annually',
    endDate: undefined,
    reminderDaysBefore: 15,
    reminderEnabled: true,
    color: '#10b981',
    linkedEntityId: 'ins_004',
    linkedEntityType: 'insurance',
    priority: 'medium',
    notes: 'Vehicle: Dhaka Metro Ga-45-8921. Premium: ৳32,500.',
    tags: ['insurance', 'motor-insurance', 'pioneer', 'annual'],
  },

  // ==================== Subscription (aggregated — not a 1:1 bill duplicate) ====================
  {
    id: 'cal_010',
    title: 'Netflix + Spotify Subscription',
    description: 'Monthly streaming subscriptions.',
    category: 'subscription',
    status: 'upcoming',
    amount: 1350,
    currency: 'BDT',
    eventDate: '2026-05-12T00:00:00.000Z',
    recurrence: 'monthly',
    recurrenceDayOfMonth: 12,
    reminderDaysBefore: 0,
    reminderEnabled: false,
    color: '#8b5cf6',
    priority: 'low',
    notes: 'Netflix: ৳900 (Premium). Spotify: ৳450 (Premium). Auto-billed via card.',
    tags: ['subscription', 'netflix', 'spotify', 'monthly', 'entertainment'],
  },

  // ==================== Recently Completed (April 2026) ====================
  {
    id: 'cal_025',
    title: 'Salary — April 2026',
    description: 'Monthly salary received for April 2026.',
    category: 'salary',
    status: 'completed',
    amount: 185000,
    currency: 'BDT',
    eventDate: '2026-04-28T00:00:00.000Z',
    recurrence: 'monthly',
    recurrenceDayOfMonth: 28,
    reminderDaysBefore: 0,
    reminderEnabled: false,
    color: '#22c55e',
    priority: 'high',
    notes: 'Credited to City Bank salary account.',
    tags: ['income', 'salary', 'monthly', 'completed'],
  },

  // ==================== NOTE: Bill-derived events removed ====================
  // The following calendar events were REMOVED because they duplicate Bill records.
  // The calendar UI should auto-derive these from the Bill store:
  //   cal_001 (DBBL Home Loan EMI) → bill_009
  //   cal_002 (Personal Loan EMI) → bill_010
  //   cal_003 (Car Loan EMI) → bill_011
  //   cal_004 (MetLife Annual Premium) → bill_012
  //   cal_005 (Guardian Life Renewal) → bill_013
  //   cal_007 (WASA Water Bill) → bill_003
  //   cal_008 (DESCO Electricity) → bill_002
  //   cal_009 (Internet Bill) → bill_005
  //   cal_017 (Advance Tax Q2) → bill_018
  //   cal_019 (Vehicle Service) → bill_017
  //   cal_024 (Home Loan EMI April completed) → bill_009 payment
  //   cal_026 (Credit Card overdue) → bill_014
];
