import type { DocumentVaultItem } from '../types';

export const mockDocuments: DocumentVaultItem[] = [
  // ==================== Tax Returns ====================
  {
    id: 'doc_001',
    name: 'Tax Return FY 2024-25',
    description: 'Individual income tax return for assessment year 2024-25. Filed online through NBR portal.',
    category: 'tax_return',
    format: 'pdf',
    status: 'active',
    fileSize: 2458624,
    fileName: 'Tax_Return_FY2024-25.pdf',
    filePath: '/vault/tax/Tax_Return_FY2024-25.pdf',
    tags: ['tax', 'income-tax', 'nbr', 'fy2025'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2025-11-30T00:00:00.000Z',
    expiryDate: undefined,
    linkedEntityId: undefined,
    linkedEntityType: undefined,
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2025-11-30', note: 'Filed with NBR', fileSize: 2458624 },
    ],
    isEncrypted: false,
    uploadedBy: 'Rafiq Ahmed',
    source: 'download',
    notes: 'Tax reference: 450821-Dhaka-36. Total income declared: ৳18,50,000. Tax paid: ৳1,85,000.',
  },
  {
    id: 'doc_002',
    name: 'Tax Return FY 2023-24',
    description: 'Individual income tax return for assessment year 2023-24.',
    category: 'tax_return',
    format: 'pdf',
    status: 'archived',
    fileSize: 1984512,
    fileName: 'Tax_Return_FY2023-24.pdf',
    filePath: '/vault/tax/Tax_Return_FY2023-24.pdf',
    tags: ['tax', 'income-tax', 'nbr', 'fy2024', 'archived'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2024-11-30T00:00:00.000Z',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2024-11-30', note: 'Filed with NBR', fileSize: 1984512 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'download',
    notes: 'Total income: ৳15,20,000. Tax paid: ৳1,27,500.',
  },
  {
    id: 'doc_003',
    name: 'Tax Return FY 2022-23',
    description: 'Individual income tax return for assessment year 2022-23.',
    category: 'tax_return',
    format: 'pdf',
    status: 'archived',
    fileSize: 1843200,
    fileName: 'Tax_Return_FY2022-23.pdf',
    filePath: '/vault/tax/Tax_Return_FY2022-23.pdf',
    tags: ['tax', 'income-tax', 'nbr', 'fy2023', 'archived'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2023-11-30T00:00:00.000Z',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2023-11-30', note: 'Filed with NBR', fileSize: 1843200 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'download',
  },

  // ==================== Insurance Policies ====================
  {
    id: 'doc_004',
    name: 'MetLife Jiban Suraksha Policy',
    description: 'Life insurance policy document — Jiban Suraksha plan. Policy covers life, critical illness rider, and accidental death benefit.',
    category: 'insurance_policy',
    format: 'pdf',
    status: 'active',
    fileSize: 3145728,
    fileName: 'MetLife_JibanSuraksha_Policy.pdf',
    filePath: '/vault/insurance/MetLife_JibanSuraksha.pdf',
    tags: ['insurance', 'life-insurance', 'metlife', 'policy'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2021-01-15T00:00:00.000Z',
    expiryDate: '2041-01-14T23:59:59.000Z',
    reminderBeforeDays: 30,
    linkedEntityId: 'ins_001',
    linkedEntityType: 'insurance',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2021-01-15', note: 'Original policy document', fileSize: 3145728 },
    ],
    isEncrypted: true,
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'Policy number: ML-JBS-2021-45821. Coverage: ৳25,00,000. Keep this document secure.',
  },
  {
    id: 'doc_005',
    name: 'Guardian Life MediCare+ Certificate',
    description: 'Health insurance policy certificate — MediCare+ family plan covering self, spouse, and 1 child.',
    category: 'insurance_policy',
    format: 'pdf',
    status: 'active',
    fileSize: 1572864,
    fileName: 'GuardianLife_MediCare_Plus.pdf',
    filePath: '/vault/insurance/GuardianLife_MediCare.pdf',
    tags: ['insurance', 'health-insurance', 'guardian-life', 'policy'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2024-04-01T00:00:00.000Z',
    expiryDate: '2025-03-31T23:59:59.000Z',
    reminderBeforeDays: 30,
    linkedEntityId: 'ins_003',
    linkedEntityType: 'insurance',
    currentVersion: 2,
    versions: [
      { versionNumber: 1, date: '2023-04-01', note: 'Initial certificate', fileSize: 1441792 },
      { versionNumber: 2, date: '2024-04-01', note: 'Renewed with updated coverage', fileSize: 1572864 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'Coverage: ৳10,00,000 per annum. Network: 200+ hospitals in Bangladesh.',
  },
  {
    id: 'doc_006',
    name: 'Pioneer Insurance Motor Policy',
    description: 'Comprehensive motor insurance for Toyota Corolla X. Covers own damage, third-party liability, and personal accident.',
    category: 'insurance_policy',
    format: 'pdf',
    status: 'active',
    fileSize: 892928,
    fileName: 'Pioneer_Motor_Insurance_2025.pdf',
    filePath: '/vault/insurance/Pioneer_Motor_Insurance.pdf',
    tags: ['insurance', 'vehicle-insurance', 'motor', 'pioneer'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2025-04-10T00:00:00.000Z',
    expiryDate: '2026-04-09T23:59:59.000Z',
    reminderBeforeDays: 15,
    linkedEntityId: 'ins_004',
    linkedEntityType: 'insurance',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2025-04-10', note: 'Annual policy renewal', fileSize: 892928 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'download',
    notes: 'Vehicle: Dhaka Metro Ga-45-8921. Premium: ৳32,500/year.',
  },

  // ==================== Property Deeds ====================
  {
    id: 'doc_007',
    name: 'Dhanmondi Apartment Sale Deed',
    description: 'Registered sale deed for 3-bed apartment at House #45, Road #8, Dhanmondi R/A. Registered with Sub-Registrar, Dhaka.',
    category: 'property_deed',
    format: 'pdf',
    status: 'active',
    fileSize: 5242880,
    fileName: 'Dhanmondi_Apt_Sale_Deed.pdf',
    filePath: '/vault/property/Dhanmondi_SaleDeed.pdf',
    tags: ['property', 'deed', 'dhanmondi', 'apartment', 'registered'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2020-08-20T00:00:00.000Z',
    linkedEntityId: 'ast_001',
    linkedEntityType: 'asset',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2020-08-20', note: 'Original registered deed', fileSize: 5242880 },
    ],
    isEncrypted: true,
    sharedWith: 'Spouse — Nusrat Jahan',
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'Registration number: REG-DH-2020-45231. Sub-Registrar Office: Dhanmondi, Dhaka. Value: ৳1,85,00,000.',
  },
  {
    id: 'doc_008',
    name: 'Savar Land Mutation Certificate',
    description: 'Mutation (Namjari) certificate for 20 bigha agricultural land at Savar, Mouza Charigram.',
    category: 'property_deed',
    format: 'pdf',
    status: 'active',
    fileSize: 2097152,
    fileName: 'Savar_Land_Mutation.pdf',
    filePath: '/vault/property/Savar_Mutation.pdf',
    tags: ['property', 'land', 'mutation', 'namjari', 'savar'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2020-02-15T00:00:00.000Z',
    linkedEntityId: 'ast_003',
    linkedEntityType: 'asset',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2020-02-15', note: 'Mutation completed', fileSize: 2097152 },
    ],
    isEncrypted: true,
    sharedWith: 'Brother — Kamal Ahmed',
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'Khatian Number: KHT-DHM-45-892. 50% co-ownership with brother.',
  },

  // ==================== Bank Statements ====================
  {
    id: 'doc_009',
    name: 'DBBL Savings Account — March 2026',
    description: 'Monthly bank statement for DBBL savings account. Statement period: March 1-31, 2026.',
    category: 'bank_statement',
    format: 'pdf',
    status: 'active',
    fileSize: 524288,
    fileName: 'DBBL_Statement_Mar2026.pdf',
    filePath: '/vault/bank/DBBL_Statement_Mar2026.pdf',
    tags: ['bank', 'dbbl', 'statement', 'monthly', 'savings'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2026-03-31T00:00:00.000Z',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2026-04-01', note: 'Downloaded from iBanking', fileSize: 524288 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'download',
    notes: 'Account: DBBL Savings, ending 4521. Closing balance: ৳8,45,320.',
  },
  {
    id: 'doc_010',
    name: 'City Bank Salary Statement — Feb 2026',
    description: 'Monthly salary account statement. Feb 2026.',
    category: 'bank_statement',
    format: 'pdf',
    status: 'active',
    fileSize: 483328,
    fileName: 'CityBank_Statement_Feb2026.pdf',
    filePath: '/vault/bank/CityBank_Statement_Feb2026.pdf',
    tags: ['bank', 'city-bank', 'statement', 'salary', 'monthly'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2026-02-28T00:00:00.000Z',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2026-03-01', note: 'Auto-downloaded', fileSize: 483328 },
    ],
    uploadedBy: 'System',
    source: 'download',
    notes: 'Salary credit: ৳1,85,000 on Feb 28.',
  },

  // ==================== Investment Statements ====================
  {
    id: 'doc_011',
    name: 'Sanchaypatra FDR Certificate',
    description: '5-year Wage Earners Development Bond (WEDB) Sanchaypatra. Issued by Bangladesh Bank.',
    category: 'investment_statement',
    format: 'pdf',
    status: 'active',
    fileSize: 1048576,
    fileName: 'Sanchaypatra_WEDB_Cert.pdf',
    filePath: '/vault/investment/Sanchaypatra_WEDB.pdf',
    tags: ['investment', 'sanchaypatra', 'wedb', 'bangladesh-bank', 'bond'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2023-06-15T00:00:00.000Z',
    expiryDate: '2028-06-14T23:59:59.000Z',
    reminderBeforeDays: 60,
    linkedEntityId: 'inv_003',
    linkedEntityType: 'investment',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2023-06-15', note: 'Original certificate', fileSize: 1048576 },
    ],
    isEncrypted: true,
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'Bond value: ৳10,00,000. Interest rate: 11.03% (tax-free). Matures June 2028.',
  },
  {
    id: 'doc_012',
    name: 'IDLC DPS Statement — Q4 2025',
    description: 'Quarterly DPS statement from IDLC Finance. Shows deposit history and projected maturity amount.',
    category: 'investment_statement',
    format: 'pdf',
    status: 'active',
    fileSize: 367001,
    fileName: 'IDLC_DPS_Q4_2025.pdf',
    filePath: '/vault/investment/IDLC_DPS_Q4_2025.pdf',
    tags: ['investment', 'dps', 'idlc', 'statement', 'quarterly'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2025-12-31T00:00:00.000Z',
    linkedEntityId: 'inv_002',
    linkedEntityType: 'investment',
    currentVersion: 4,
    versions: [
      { versionNumber: 1, date: '2025-03-31', note: 'Q1 2025 statement', fileSize: 344064 },
      { versionNumber: 2, date: '2025-06-30', note: 'Q2 2025 statement', fileSize: 352256 },
      { versionNumber: 3, date: '2025-09-30', note: 'Q3 2025 statement', fileSize: 359424 },
      { versionNumber: 4, date: '2025-12-31', note: 'Q4 2025 statement', fileSize: 367001 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'Monthly deposit: ৳25,000. 24 deposits made. Maturity: Dec 2026.',
  },

  // ==================== Loan Documents ====================
  {
    id: 'doc_013',
    name: 'DBBL Home Loan Agreement',
    description: 'Home loan sanction letter and agreement for Dhanmondi apartment. 20-year tenure.',
    category: 'loan_document',
    format: 'pdf',
    status: 'active',
    fileSize: 4194304,
    fileName: 'DBBL_HomeLoan_Agreement.pdf',
    filePath: '/vault/loans/DBBL_HomeLoan.pdf',
    tags: ['loan', 'home-loan', 'dbbl', 'mortgage', 'agreement'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2020-07-01T00:00:00.000Z',
    expiryDate: '2040-06-30T23:59:59.000Z',
    linkedEntityId: 'mort_001',
    linkedEntityType: 'mortgage',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2020-07-01', note: 'Original loan agreement', fileSize: 4194304 },
    ],
    isEncrypted: true,
    sharedWith: 'Spouse — Nusrat Jahan',
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'Loan amount: ৳1,20,00,000. Interest: 9.5% fixed. EMI: ৳1,11,628. Loan ID: HL-DBBL-2020-4521.',
  },

  // ==================== Contracts ====================
  {
    id: 'doc_014',
    name: 'Gulshan Office Rental Agreement',
    description: 'Annual rental agreement for commercial office space at Gulshan Avenue. Tenant: TechNova Solutions Ltd.',
    category: 'contract',
    format: 'pdf',
    status: 'active',
    fileSize: 2621440,
    fileName: 'Gulshan_Rental_Agreement_2026.pdf',
    filePath: '/vault/contracts/Gulshan_Rental_2026.pdf',
    tags: ['contract', 'rental', 'commercial', 'gulshan', 'office'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2026-01-01T00:00:00.000Z',
    expiryDate: '2026-12-31T23:59:59.000Z',
    reminderBeforeDays: 60,
    currentVersion: 2,
    versions: [
      { versionNumber: 1, date: '2025-01-01', note: 'Initial rental agreement', fileSize: 2560000 },
      { versionNumber: 2, date: '2026-01-01', note: 'Renewed with 10% rent increase', fileSize: 2621440 },
    ],
    sharedWith: 'Tenant — TechNova Solutions, Advocate — Rahim & Associates',
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'Monthly rent: ৳85,000. Security deposit: ৳5,10,000. Annual increment clause: 10%.',
  },
  {
    id: 'doc_015',
    name: 'Employment Contract — Rafiq Ahmed',
    description: 'Current employment contract with SoftwareBangladesh Ltd. Position: Senior Software Engineer.',
    category: 'contract',
    format: 'pdf',
    status: 'active',
    fileSize: 1572864,
    fileName: 'Employment_Contract_SoftBD.pdf',
    filePath: '/vault/contracts/Employment_Contract.pdf',
    tags: ['contract', 'employment', 'job', 'softbangladesh'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2024-03-01T00:00:00.000Z',
    expiryDate: '2027-02-28T23:59:59.000Z',
    reminderBeforeDays: 90,
    currentVersion: 2,
    versions: [
      { versionNumber: 1, date: '2022-03-01', note: 'Initial contract', fileSize: 1400000 },
      { versionNumber: 2, date: '2024-03-01', note: 'Contract renewal with promotion', fileSize: 1572864 },
    ],
    isEncrypted: false,
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'Monthly salary: ৳1,85,000. Annual bonus: 2 months basic. Probation period completed.',
  },

  // ==================== Receipts ====================
  {
    id: 'doc_016',
    name: 'Toyota Corolla X — Purchase Invoice',
    description: 'Purchase invoice and delivery note for Toyota Corolla X 1.6L from Toyota Eastern Motors.',
    category: 'receipt',
    format: 'pdf',
    status: 'active',
    fileSize: 745472,
    fileName: 'Toyota_Corolla_Invoice.pdf',
    filePath: '/vault/receipts/Toyota_Corolla_Invoice.pdf',
    tags: ['receipt', 'vehicle', 'toyota', 'purchase', 'invoice'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2023-04-10T00:00:00.000Z',
    linkedEntityId: 'ast_004',
    linkedEntityType: 'asset',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2023-04-10', note: 'Original purchase invoice', fileSize: 745472 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'Invoice: INV-TEM-2023-7891. Total: ৳33,50,000 (on-road). Color: White.',
  },
  {
    id: 'doc_017',
    name: 'Otobi Furniture — Receipt',
    description: 'Purchase receipt for bedroom furniture set from Otobi, Dhanmondi branch.',
    category: 'receipt',
    format: 'jpg',
    status: 'active',
    fileSize: 2097152,
    fileName: 'Otobi_Furniture_Receipt.jpg',
    filePath: '/vault/receipts/Otobi_Receipt.jpg',
    tags: ['receipt', 'furniture', 'otobi', 'bedroom'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2020-07-01T00:00:00.000Z',
    linkedEntityId: 'ast_009',
    linkedEntityType: 'asset',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2020-07-01', note: 'Scanned receipt photo', fileSize: 2097152 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
  },

  // ==================== ID Proofs ====================
  {
    id: 'doc_018',
    name: 'National ID Card — Rafiq Ahmed',
    description: 'Bangladesh National ID card scan. NID number: 4508215678.',
    category: 'id_proof',
    format: 'jpg',
    status: 'active',
    fileSize: 1572864,
    fileName: 'NID_Rafiq_Ahmed.jpg',
    filePath: '/vault/id/NID_Rafiq_Ahmed.jpg',
    tags: ['id', 'nid', 'national-id', 'identity'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2023-05-20T00:00:00.000Z',
    currentVersion: 2,
    versions: [
      { versionNumber: 1, date: '2018-05-20', note: 'Old NID (smart card)', fileSize: 1200000 },
      { versionNumber: 2, date: '2023-05-20', note: 'Updated NID with new address', fileSize: 1572864 },
    ],
    isEncrypted: true,
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'NID: 4508215678. DOB: 1990-03-15. Address: House #45, Road #8, Dhanmondi, Dhaka.',
  },
  {
    id: 'doc_019',
    name: 'Passport — Rafiq Ahmed',
    description: 'Bangladesh passport bio-page scan. Ordinary passport.',
    category: 'id_proof',
    format: 'jpg',
    status: 'active',
    fileSize: 2097152,
    fileName: 'Passport_Rafiq_Ahmed.jpg',
    filePath: '/vault/id/Passport_Rafiq.jpg',
    tags: ['id', 'passport', 'travel', 'identity'],
    isFavorite: true,
    isImportant: true,
    documentDate: '2024-01-10T00:00:00.000Z',
    expiryDate: '2029-01-09T23:59:59.000Z',
    reminderBeforeDays: 180,
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2024-01-10', note: 'New passport issued', fileSize: 2097152 },
    ],
    isEncrypted: true,
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'Passport number: BR 0456789. Type: Ordinary. Expiry: Jan 2029.',
  },

  // ==================== Medical Records ====================
  {
    id: 'doc_020',
    name: 'Annual Health Checkup Report 2025',
    description: 'Complete health checkup report from Square Hospital. Includes blood work, ECG, chest X-ray, and doctor consultation summary.',
    category: 'medical_record',
    format: 'pdf',
    status: 'active',
    fileSize: 3932160,
    fileName: 'Health_Checkup_2025.pdf',
    filePath: '/vault/medical/HealthCheckup_2025.pdf',
    tags: ['medical', 'health', 'checkup', 'square-hospital', 'annual'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2025-09-15T00:00:00.000Z',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2025-09-15', note: 'Post-checkup report', fileSize: 3932160 },
    ],
    isEncrypted: false,
    uploadedBy: 'Rafiq Ahmed',
    source: 'email',
    notes: 'All parameters normal. BMI: 24.2. Cholesterol slightly elevated (215 mg/dL). Doctor advised dietary adjustments.',
  },

  // ==================== Education Certificates ====================
  {
    id: 'doc_021',
    name: 'BSc CSE Degree Certificate — BUET',
    description: 'Bachelor of Science in Computer Science & Engineering from Bangladesh University of Engineering & Technology.',
    category: 'education_certificate',
    format: 'pdf',
    status: 'active',
    fileSize: 892928,
    fileName: 'BUET_BSc_CSE_Degree.pdf',
    filePath: '/vault/education/BUET_Degree.pdf',
    tags: ['education', 'degree', 'buet', 'cse', 'bachelor'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2012-11-30T00:00:00.000Z',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2012-11-30', note: 'Original degree scan', fileSize: 892928 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'CGPA: 3.72/4.00. Session: 2008-09 to 2012-13. Roll: 0805052.',
  },

  // ==================== Vehicle Registration ====================
  {
    id: 'doc_022',
    name: 'Vehicle Registration — Toyota Corolla X',
    description: 'BRTA vehicle registration certificate (RC book) for Toyota Corolla X.',
    category: 'vehicle_registration',
    format: 'pdf',
    status: 'active',
    fileSize: 1843200,
    fileName: 'BRTA_RC_Corolla_X.pdf',
    filePath: '/vault/vehicle/BRTA_RC_Corolla.pdf',
    tags: ['vehicle', 'registration', 'brta', 'rc-book', 'toyota'],
    isFavorite: false,
    isImportant: true,
    documentDate: '2023-04-15T00:00:00.000Z',
    linkedEntityId: 'ast_004',
    linkedEntityType: 'asset',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2023-04-15', note: 'Registration completed', fileSize: 1843200 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'scanned',
    notes: 'Registration: Dhaka Metro Ga-45-8921. Engine: 1NZ-FE-892456. Chassis: SB1K93BE50E892456.',
  },

  // ==================== Invoices ====================
  {
    id: 'doc_023',
    name: 'Summit Electronics — Samsung TV Invoice',
    description: 'Purchase invoice for Samsung 65" Crystal UHD Smart TV from Summit Electronics, Bashundhara City.',
    category: 'invoice',
    format: 'pdf',
    status: 'active',
    fileSize: 327680,
    fileName: 'Summit_SamsungTV_Invoice.pdf',
    filePath: '/vault/invoices/Summit_SamsungTV.pdf',
    tags: ['invoice', 'electronics', 'samsung', 'tv', 'purchase'],
    isFavorite: false,
    isImportant: false,
    documentDate: '2023-07-10T00:00:00.000Z',
    linkedEntityId: 'ast_007',
    linkedEntityType: 'asset',
    currentVersion: 1,
    versions: [
      { versionNumber: 1, date: '2023-07-10', note: 'Purchase invoice', fileSize: 327680 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'download',
    notes: 'Model: CU8000 65". Price: ৳1,15,000. Warranty: 2 years.',
  },

  // ==================== Other ====================
  {
    id: 'doc_024',
    name: 'Family Budget Spreadsheet 2026',
    description: 'Annual family budget planning spreadsheet with monthly breakdowns for income, expenses, savings targets.',
    category: 'other',
    format: 'xlsx',
    status: 'active',
    fileSize: 524288,
    fileName: 'Family_Budget_2026.xlsx',
    filePath: '/vault/other/Family_Budget_2026.xlsx',
    tags: ['budget', 'planning', 'spreadsheet', 'family', '2026'],
    isFavorite: true,
    isImportant: false,
    documentDate: '2026-01-01T00:00:00.000Z',
    currentVersion: 3,
    versions: [
      { versionNumber: 1, date: '2026-01-01', note: 'Initial budget draft', fileSize: 450560 },
      { versionNumber: 2, date: '2026-02-15', note: 'Updated with Jan actuals', fileSize: 487424 },
      { versionNumber: 3, date: '2026-04-01', note: 'Updated with Q1 actuals', fileSize: 524288 },
    ],
    uploadedBy: 'Rafiq Ahmed',
    source: 'upload',
    notes: 'Includes separate sheets for income, needs, wants, savings/investments tracking.',
  },
];
