import type { SavingsGoal } from '../types';

// Helper: generate contributions spread over past months
function makeContributions(startMonth: number, monthlyAmount: number, months: number, variance: number = 0): { contributions: any[]; totalContributed: number } {
  const contributions: any[] = [];
  let totalContributed = 0;
  const now = new Date();
  for (let i = 0; i < months; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - (months - 1 - i), 5);
    const amount = monthlyAmount + Math.round((Math.random() - 0.5) * variance * 2);
    if (amount > 0) {
      contributions.push({
        id: `sgc_${Date.now()}_${i}_${Math.random().toString(36).substring(2, 5)}`,
        amount,
        date: d.toISOString(),
        note: i === 0 ? 'Initial contribution' : `Monthly savings - month ${i + 1}`,
      });
      totalContributed += amount;
    }
  }
  return { contributions, totalContributed };
}

function makeMilestones(currentPercent: number): any[] {
  return [
    { id: 'ms_25', percent: 25, label: 'Getting Started!', achieved: currentPercent >= 25, achievedDate: currentPercent >= 25 ? '2025-09-15T10:00:00Z' : undefined },
    { id: 'ms_50', percent: 50, label: 'Halfway There!', achieved: currentPercent >= 50, achievedDate: currentPercent >= 50 ? '2025-12-20T10:00:00Z' : undefined },
    { id: 'ms_75', percent: 75, label: 'Almost There!', achieved: currentPercent >= 75, achievedDate: currentPercent >= 75 ? '2026-03-10T10:00:00Z' : undefined },
    { id: 'ms_100', percent: 100, label: 'Goal Complete!', achieved: currentPercent >= 100, achievedDate: currentPercent >= 100 ? '2026-04-18T10:00:00Z' : undefined },
  ];
}

// 1. Emergency Fund — 87% done, high priority, almost there
const emergencyContribs = makeContributions(12, 18000, 12, 5000);
export const mockSavingsGoals: SavingsGoal[] = [
  {
    id: 'sg_emergency_001',
    createdAt: '2025-04-10T06:00:00Z',
    updatedAt: '2026-04-15T12:00:00Z',
    name: 'Emergency Fund',
    description: 'Build a 6-month expense safety net. Essential for financial security in uncertain times.',
    category: 'emergency_fund',
    status: 'active',
    targetAmount: 500000,
    currentAmount: emergencyContribs.totalContributed,
    currency: 'BDT',
    startDate: '2025-04-01T00:00:00Z',
    targetDate: '2026-09-30T00:00:00Z',
    monthlyContributionAmount: 18000,
    autoContributeEnabled: true,
    autoContributeDayOfMonth: 5,
    contributions: emergencyContribs.contributions,
    totalContributed: emergencyContribs.totalContributed,
    totalWithdrawn: 0,
    contributionCount: emergencyContribs.contributions.length,
    milestones: makeMilestones(Math.round((emergencyContribs.totalContributed / 500000) * 100)),
    motivationalQuote: 'An emergency fund is not about the money. It is about peace of mind.',
    coverColor: '#10b981',
    coverIcon: '🛡️',
    currentStreak: 12,
    longestStreak: 12,
    priority: 'high',
    bankAccountId: 'ba_1',
    notes: 'Keep this untouched unless absolute emergency. 6 months of living expenses target.',
    tags: ['essential', 'priority', 'safety-net'],
  },

  // 2. Hajj Fund — 42% done, long-term, ongoing contributions
  {
    id: 'sg_hajj_002',
    createdAt: '2024-06-01T06:00:00Z',
    updatedAt: '2026-04-10T12:00:00Z',
    name: 'Hajj Fund',
    description: 'Saving for the sacred pilgrimage to Makkah. A lifelong dream and spiritual obligation.',
    category: 'vacation',
    status: 'active',
    targetAmount: 500000,
    currentAmount: 210000,
    currency: 'BDT',
    startDate: '2024-06-01T00:00:00Z',
    targetDate: '2027-12-31T00:00:00Z',
    monthlyContributionAmount: 15000,
    autoContributeEnabled: true,
    autoContributeDayOfMonth: 10,
    contributions: [],
    totalContributed: 210000,
    totalWithdrawn: 0,
    contributionCount: 22,
    milestones: makeMilestones(42),
    motivationalQuote: 'The best investment is investing in your hereafter.',
    coverColor: '#8b5cf6',
    coverIcon: '🕋',
    currentStreak: 8,
    longestStreak: 15,
    priority: 'high',
    bankAccountId: 'ba_1',
    tags: ['spiritual', 'long-term', 'dream'],
  },

  // 3. iPhone 17 Pro — 72% done, near completion
  {
    id: 'sg_iphone_003',
    createdAt: '2025-10-01T06:00:00Z',
    updatedAt: '2026-04-12T12:00:00Z',
    name: 'iPhone 17 Pro',
    description: 'Upgrading from my current phone. Saving up to buy it outright instead of EMI.',
    category: 'gadget',
    status: 'active',
    targetAmount: 185000,
    currentAmount: 133000,
    currency: 'BDT',
    startDate: '2025-10-01T00:00:00Z',
    targetDate: '2026-06-30T00:00:00Z',
    monthlyContributionAmount: 20000,
    autoContributeEnabled: false,
    contributions: [],
    totalContributed: 133000,
    totalWithdrawn: 0,
    contributionCount: 6,
    milestones: makeMilestones(72),
    motivationalQuote: 'Small steps every month lead to big rewards!',
    coverColor: '#3b82f6',
    coverIcon: '📱',
    currentStreak: 6,
    longestStreak: 6,
    priority: 'medium',
    notes: 'Wait for release in Bangladesh. Buy unlocked from Apple Store.',
    tags: ['tech', 'short-term', 'no-emi'],
  },

  // 4. Home Down Payment — 18% done, long-term big goal
  {
    id: 'sg_home_004',
    createdAt: '2025-08-01T06:00:00Z',
    updatedAt: '2026-04-08T12:00:00Z',
    name: 'Home Down Payment',
    description: 'Saving for the down payment on a 3-bedroom apartment in Dhanmondi or Bashundhara R/A.',
    category: 'home',
    status: 'active',
    targetAmount: 3000000,
    currentAmount: 540000,
    currency: 'BDT',
    startDate: '2025-08-01T00:00:00Z',
    targetDate: '2030-12-31T00:00:00Z',
    monthlyContributionAmount: 25000,
    autoContributeEnabled: true,
    autoContributeDayOfMonth: 1,
    contributions: [],
    totalContributed: 540000,
    totalWithdrawn: 0,
    contributionCount: 8,
    milestones: makeMilestones(18),
    motivationalQuote: 'A home is not just an address. It is where your story begins.',
    coverColor: '#f59e0b',
    coverIcon: '🏠',
    currentStreak: 8,
    longestStreak: 8,
    priority: 'high',
    tags: ['long-term', 'property', 'dhaka', 'dream-home'],
  },

  // 5. MS in CS Abroad — 55% done, education goal
  {
    id: 'sg_education_005',
    createdAt: '2025-01-15T06:00:00Z',
    updatedAt: '2026-04-14T12:00:00Z',
    name: 'MS in Computer Science (USA)',
    description: 'Tuition + living expenses for a 2-year MS program at a US university. Application prep included.',
    category: 'education',
    status: 'active',
    targetAmount: 4500000,
    currentAmount: 2475000,
    currency: 'BDT',
    startDate: '2025-01-15T00:00:00Z',
    targetDate: '2027-08-01T00:00:00Z',
    monthlyContributionAmount: 40000,
    autoContributeEnabled: true,
    autoContributeDayOfMonth: 5,
    contributions: [],
    totalContributed: 2475000,
    totalWithdrawn: 0,
    contributionCount: 15,
    milestones: makeMilestones(55),
    motivationalQuote: 'Education is the most powerful weapon which you can use to change the world.',
    coverColor: '#6366f1',
    coverIcon: '🎓',
    currentStreak: 15,
    longestStreak: 15,
    priority: 'high',
    bankAccountId: 'ba_2',
    notes: 'Targeting Fall 2027 intake. GRE prep and application costs included.',
    tags: ['education', 'usa', 'career', 'long-term'],
  },

  // 6. Sister Wedding Gift — 30% done, with a deadline
  {
    id: 'sg_wedding_006',
    createdAt: '2025-11-01T06:00:00Z',
    updatedAt: '2026-04-05T12:00:00Z',
    name: 'Sister Wedding Gift',
    description: 'Special gift fund for my sister\'s wedding in December 2026. Want to give something memorable.',
    category: 'wedding',
    status: 'active',
    targetAmount: 200000,
    currentAmount: 60000,
    currency: 'BDT',
    startDate: '2025-11-01T00:00:00Z',
    targetDate: '2026-12-15T00:00:00Z',
    monthlyContributionAmount: 12000,
    autoContributeEnabled: true,
    autoContributeDayOfMonth: 15,
    contributions: [],
    totalContributed: 60000,
    totalWithdrawn: 0,
    contributionCount: 5,
    milestones: makeMilestones(30),
    motivationalQuote: 'The best gifts come from the heart — and a little planning.',
    coverColor: '#ec4899',
    coverIcon: '💐',
    currentStreak: 5,
    longestStreak: 5,
    priority: 'medium',
    tags: ['family', 'gift', 'wedding', '2026'],
  },

  // 7. New Laptop Fund — COMPLETED!
  {
    id: 'sg_laptop_007',
    createdAt: '2025-05-01T06:00:00Z',
    updatedAt: '2026-02-20T12:00:00Z',
    name: 'MacBook Pro M4',
    description: 'Bought the MacBook Pro M4 for development work. Goal achieved through consistent monthly saving!',
    category: 'gadget',
    status: 'completed',
    targetAmount: 230000,
    currentAmount: 230000,
    currency: 'BDT',
    startDate: '2025-05-01T00:00:00Z',
    completedDate: '2026-02-20T10:00:00Z',
    monthlyContributionAmount: 23000,
    autoContributeEnabled: false,
    contributions: [],
    totalContributed: 230000,
    totalWithdrawn: 0,
    contributionCount: 10,
    milestones: makeMilestones(100),
    motivationalQuote: 'Every achievement starts with the decision to try.',
    coverColor: '#64748b',
    coverIcon: '💻',
    currentStreak: 0,
    longestStreak: 10,
    priority: 'medium',
    notes: 'Purchased from Apple Store BD. 16GB RAM, 512GB SSD.',
    tags: ['completed', 'tech', 'work', 'achievement'],
  },

  // 8. Family Vacation Cox Bazar — 5% just started
  {
    id: 'sg_vacation_008',
    createdAt: '2026-03-15T06:00:00Z',
    updatedAt: '2026-04-10T12:00:00Z',
    name: 'Family Vacation - Cox Bazar',
    description: 'Week-long family trip to Cox Bazar with parents and siblings. Hotel, food, and transport.',
    category: 'vacation',
    status: 'active',
    targetAmount: 150000,
    currentAmount: 8000,
    currency: 'BDT',
    startDate: '2026-03-15T00:00:00Z',
    targetDate: '2026-12-01T00:00:00Z',
    monthlyContributionAmount: 15000,
    autoContributeEnabled: false,
    contributions: [],
    totalContributed: 8000,
    totalWithdrawn: 0,
    contributionCount: 1,
    milestones: makeMilestones(5),
    motivationalQuote: 'The journey of a thousand miles begins with a single step — and a single taka!',
    coverColor: '#06b6d4',
    coverIcon: '🏖️',
    currentStreak: 1,
    longestStreak: 1,
    priority: 'low',
    tags: ['vacation', 'family', 'coxbazar', 'memories'],
  },
];
