# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_phone', models.CharField(blank=True, default='', max_length=50)),
                ('borrower_email', models.EmailField(blank=True, default='', max_length=254)),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('business', 'Business'), ('other', 'Other')], max_length=20)),
                ('principal_amount', models.BigIntegerField()),
                ('current_balance', models.BigIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_interest_amount', models.BigIntegerField(default=0)),
                ('total_repayable_amount', models.BigIntegerField()),
                ('total_repaid_amount', models.BigIntegerField(default=0)),
                ('issued_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('repayment_schedule', models.CharField(blank=True, choices=[('lump_sum', 'Lump Sum'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_repaid', 'Partially Repaid'), ('fully_repaid', 'Fully Repaid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lending',
                'verbose_name_plural': 'Lendings',
                'db_table': 'lendings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LendingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_number', models.IntegerField(default=1)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lending.lending')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lending Payment',
                'verbose_name_plural': 'Lending Payments',
                'db_table': 'lending_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
