# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('emergency_fund', 'Emergency Fund'), ('vacation', 'Vacation'), ('home', 'Home'), ('car', 'Car'), ('education', 'Education'), ('wedding', 'Wedding'), ('retirement', 'Retirement'), ('gadget', 'Gadget'), ('gift', 'Gift'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=50)),
                ('target_amount', models.BigIntegerField(default=0)),
                ('current_amount', models.BigIntegerField(default=0)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('monthly_contribution_amount', models.BigIntegerField(default=0)),
                ('auto_contribute_enabled', models.BooleanField(default=False)),
                ('auto_contribute_day_of_month', models.IntegerField(blank=True, null=True)),
                ('total_contributed', models.BigIntegerField(default=0)),
                ('total_withdrawn', models.BigIntegerField(default=0)),
                ('contribution_count', models.IntegerField(default=0)),
                ('motivational_quote', models.TextField(blank=True, default='')),
                ('cover_color', models.CharField(blank=True, default='', max_length=7)),
                ('cover_icon', models.CharField(blank=True, default='', max_length=255)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50)),
                ('bank_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Goal',
                'verbose_name_plural': 'Savings Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoalContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('bank_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='savings_goal.savingsgoal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Goal Contribution',
                'verbose_name_plural': 'Savings Goal Contributions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoalMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.IntegerField(default=0)),
                ('label', models.CharField(default='', max_length=255)),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='savings_goal.savingsgoal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Savings Goal Milestone',
                'verbose_name_plural': 'Savings Goal Milestones',
                'ordering': ['percent'],
            },
        ),
    ]
