# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_account_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('card_number', models.CharField(max_length=4)),
                ('holder_name', models.CharField(max_length=255)),
                ('expiry_date', models.CharField(max_length=7)),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'Amex'), ('discover', 'Discover')], max_length=20)),
                ('credit_limit', models.BigIntegerField(blank=True, null=True)),
                ('current_balance', models.BigIntegerField(default=0)),
                ('billing_cycle', models.JSONField(default=dict)),
                ('due_date', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('secondary_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('secondary_credit_limit', models.BigIntegerField(blank=True, null=True)),
                ('secondary_current_balance', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-created_at'],
            },
        ),
    ]
