# Generated by Django 5.2.12 on 2026-04-25 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_remove_transaction_category_id_transaction_category_and_more"),
        ("card", "0002_remove_card_bank_account_id_card_bank_account_and_more"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='card',
        #     name='bank_account',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank.bankaccount'),
        # ),
    ]
