# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(choices=[('needs', 'Needs'), ('wants', 'Wants'), ('savings', 'Savings'), ('investments', 'Investments')], default='needs', max_length=20)),
                ('budget_limit', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
                ('bank_account_id', models.UUIDField()),
                ('card_id', models.UUIDField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_cycle', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
