# Generated by Django 5.2.12 on 2026-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='currency',
            field=models.CharField(default='BDT', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bank_account_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
