# Generated by Django 5.2.12 on 2026-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='currency',
            field=models.CharField(default='BDT', max_length=3),
        ),
    ]
