# Generated by Django 5.2.12 on 2026-04-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_incomesource_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='bank_account_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
