# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fdr', 'FDR'), ('dps', 'DPS'), ('sanchaypatra', 'Sanchaypatra'), ('stock', 'Stock'), ('mutual_fund', 'Mutual Fund'), ('gold', 'Gold'), ('bond', 'Bond'), ('other', 'Other')], max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('invested_amount', models.BigIntegerField(default=0)),
                ('current_value', models.BigIntegerField(default=0)),
                ('total_returns', models.BigIntegerField(default=0)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('avg_buy_price', models.BigIntegerField(default=0)),
                ('current_unit_price', models.BigIntegerField(default=0)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compounding', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('at_maturity', 'At Maturity')], default='', max_length=20)),
                ('tax_on_interest', models.BooleanField(default=False)),
                ('monthly_deposit_amount', models.BigIntegerField(default=0)),
                ('total_deposited_so_far', models.BigIntegerField(default=0)),
                ('deposit_count', models.IntegerField(default=0)),
                ('stock_symbol', models.CharField(blank=True, default='', max_length=50)),
                ('stock_exchange', models.CharField(blank=True, choices=[('DSE', 'DSE'), ('CSE', 'CSE'), ('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('other', 'Other')], default='', max_length=10)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('purity', models.CharField(blank=True, choices=[('18k', '18K'), ('21k', '21K'), ('22k', '22K'), ('24k', '24K')], default='', max_length=5)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('sold', 'Sold'), ('redeemed', 'Redeemed'), ('closed', 'Closed')], default='active', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('dividend', 'Dividend'), ('interest', 'Interest'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus'), ('maturity', 'Maturity')], max_length=20)),
                ('amount', models.BigIntegerField(default=0)),
                ('units', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_price', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('bank_account_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investment.investment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Transaction',
                'verbose_name_plural': 'Investment Transactions',
                'db_table': 'investment_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
