"""
Auth API for FinLife.
OTP-based email verification for registration, login, and password changes.

Flow:
  Register          → OTP sent to email → Verify OTP → Tokens returned (account activated)
  Login             → Validate credentials → OTP sent → Verify OTP → Tokens returned
  Forgot Password   → Enter email → OTP sent → Verify OTP + New Password → Password reset
  Change Password   → Verify current password → OTP sent → Verify OTP → Password changed
"""

from django.contrib.auth import get_user_model
from django.db import IntegrityError
from ninja import Router

from common.permissions import BearerAuth
from .schemas import (
    ChangePasswordConfirmIn,
    ChangePasswordIn,
    ForgotPasswordConfirmIn,
    ForgotPasswordIn,
    MessageOut,
    NotificationPreferenceSchema,
    OTPVerifyIn,
    RefreshTokenIn,
    RefreshTokenOut,
    ResendOtpIn,
    TokenOut,
    UserCreate,
    UserLogin,
    UserOut,
    UserUpdate,
)

User = get_user_model()
router = Router(tags=["Auth"])


# ==================== Registration ====================


@router.post("/register/", response={201: MessageOut, 400: MessageOut})
async def register(request, payload: UserCreate):
    """
    Register a new user and send email verification OTP.
    Account is INACTIVE until OTP is verified.
    Returns a message — NOT tokens.
    """
    if await User.objects.filter(email=payload.email).aexists():
        return 400, {"message": "Email already registered."}

    try:
        user = await User.objects.acreate_user(
            email=payload.email,
            password=payload.password,
            name=payload.name,
            currency=payload.currency,
            date_format=payload.dateFormat,
            dark_mode=payload.darkMode,
        )
        # slug (UUID) is auto-generated by Django default=uuid.uuid4
    except (ValueError, IntegrityError) as e:
        return 400, {"message": str(e)}

    # Send verification OTP
    try:
        from .services import create_and_send_otp

        await create_and_send_otp(user.email, "register", user=user)
    except ValueError as e:
        return 400, {"message": str(e)}

    return 201, {
        "message": "Registration successful! Please check your email for a verification code."
    }


# ==================== Verify OTP ====================


@router.post("/verify-otp/", response={200: TokenOut, 401: MessageOut})
async def verify_otp_endpoint(request, payload: OTPVerifyIn):
    """
    Verify OTP code for registration or login.
    On success: activates account (if register) and returns JWT tokens.

    NOTE: change_password and forgot_password purposes are handled by their
    own confirm endpoints — this endpoint only issues tokens for register and login.
    """
    from .services import verify_otp
    from common.auth import create_token_pair

    if payload.purpose in ("change_password", "forgot_password"):
        return 401, {"message": "Use the dedicated confirm endpoint for this purpose."}

    try:
        otp = await verify_otp(payload.email, payload.otp, payload.purpose)
    except ValueError as e:
        return 401, {"message": str(e)}

    if payload.purpose == "register":
        # Activate the user account
        user = await User.objects.aget(email=payload.email)
        if not user.is_active:
            user.is_active = True
            await user.asave(update_fields=["is_active", "updated_at"])

    elif payload.purpose == "login":
        # Get user from the OTP record
        if not otp.user_id:
            return 401, {"message": "Invalid login session. Please try again."}
        user = await User.objects.aget(pk=otp.user_id)
    else:
        return 401, {"message": "Invalid purpose."}

    # Issue tokens
    tokens = create_token_pair(user)
    return {
        "access": tokens["access"],
        "refresh": tokens["refresh"],
        "token_type": "bearer",
        "user": user,
    }


# ==================== Login ====================


@router.post("/login/", response={200: MessageOut, 401: MessageOut})
async def login(request, payload: UserLogin):
    """
    Authenticate user and send OTP for login verification.
    Returns a message — NOT tokens. User must verify OTP next.
    """
    try:
        user = await User.objects.aget(email=payload.email)
    except User.DoesNotExist:
        return 401, {"message": "Invalid email or password."}

    if not await user.acheck_password(payload.password):
        return 401, {"message": "Invalid email or password."}

    if not user.is_active:
        return 401, {
            "message": "Account is not activated. Please verify your email first."
        }

    # Send OTP for login verification
    try:
        from .services import create_and_send_otp

        await create_and_send_otp(user.email, "login", user=user)
    except ValueError as e:
        return 401, {"message": str(e)}

    return 200, {"message": "OTP sent to your email for login verification."}


# ==================== Resend OTP ====================


@router.post(
    "/resend-otp/", response={200: MessageOut, 401: MessageOut, 429: MessageOut}
)
async def resend_otp(request, payload: ResendOtpIn):
    """Resend OTP for registration or login."""
    from .services import create_and_send_otp

    if payload.purpose == "register":
        if not await User.objects.filter(email=payload.email).aexists():
            return 401, {"message": "Email not registered."}
        user = await User.objects.aget(email=payload.email)
        # Don't allow resend if already active
        if user.is_active:
            return 401, {"message": "Account is already verified. Please login."}
    elif payload.purpose == "login":
        try:
            user = await User.objects.aget(email=payload.email, is_active=True)
        except User.DoesNotExist:
            return 401, {"message": "Invalid email or inactive account."}
    elif payload.purpose == "change_password":
        try:
            user = await User.objects.aget(email=payload.email, is_active=True)
        except User.DoesNotExist:
            return 401, {"message": "Invalid email."}
    elif payload.purpose == "forgot_password":
        try:
            user = await User.objects.aget(email=payload.email, is_active=True)
        except User.DoesNotExist:
            return 401, {"message": "Email not found or account is inactive."}
    else:
        return 401, {"message": "Invalid purpose."}

    try:
        await create_and_send_otp(payload.email, payload.purpose, user=user)
    except ValueError as e:
        return 429, {"message": str(e)}

    return 200, {"message": "New OTP sent to your email."}


# ==================== Refresh Token ====================


@router.post("/refresh/", response={200: RefreshTokenOut, 401: MessageOut})
async def refresh_token(request, payload: RefreshTokenIn):
    """Exchange a refresh token for new access (and optionally refresh) token."""
    from ninja_jwt.tokens import RefreshToken

    try:
        refresh = RefreshToken(payload.refresh)
        user_id = refresh.get("user_id")  # dict-like, no aget()
        if not user_id:
            return 401, {"message": "Invalid refresh token."}

        user = await User.objects.aget(pk=user_id)
        if not user.is_active:
            return 401, {"message": "User account is deactivated."}

        from common.auth import create_token_pair

        tokens = create_token_pair(user)
        return {
            "access": tokens["access"],
            "refresh": tokens["refresh"],
            "token_type": "bearer",
        }
    except Exception:
        return 401, {"message": "Invalid or expired refresh token."}


# ==================== Logout ====================


@router.post("/logout/", auth=BearerAuth(), response={200: MessageOut})
async def logout(request):
    """Logout endpoint (stateless — client discards token)."""
    return {"message": "Successfully logged out."}


# ==================== Get Current User ====================


@router.get("/me/", auth=BearerAuth(), response=UserOut)
async def get_me(request):
    """Get current authenticated user profile."""
    return request.user


# ==================== Update Current User ====================


@router.put("/me/", auth=BearerAuth(), response=UserOut)
async def update_me(request, payload: UserUpdate):
    """Update current authenticated user profile."""
    user = request.user

    update_fields = []
    if payload.name is not None:
        user.name = payload.name
        update_fields.append("name")
    if payload.avatar is not None:
        user.avatar = payload.avatar
        update_fields.append("avatar")
    if payload.currency is not None:
        user.currency = payload.currency
        update_fields.append("currency")
    if payload.dateFormat is not None:
        user.date_format = payload.dateFormat
        update_fields.append("date_format")
    if payload.darkMode is not None:
        user.dark_mode = payload.darkMode
        update_fields.append("dark_mode")
    if payload.notifications is not None:
        user.notifications = payload.notifications.model_dump()
        update_fields.append("notifications")

    if update_fields:
        await user.asave(update_fields=update_fields)
        await user.arefresh_from_db()
    return user


# ==================== Notification Preferences ====================


@router.get(
    "/me/preferences/",
    auth=BearerAuth(),
    response=NotificationPreferenceSchema,
)
async def get_preferences(request):
    """Get current user notification preferences."""
    notif = request.user.notifications
    if isinstance(notif, dict):
        return NotificationPreferenceSchema(**notif)
    return NotificationPreferenceSchema()


@router.put(
    "/me/preferences/",
    auth=BearerAuth(),
    response=NotificationPreferenceSchema,
)
async def update_preferences(request, payload: NotificationPreferenceSchema):
    """Update current user notification preferences."""
    user = request.user
    user.notifications = payload.model_dump()
    await user.asave(update_fields=["notifications", "updated_at"])
    notif = user.notifications
    if isinstance(notif, dict):
        return NotificationPreferenceSchema(**notif)
    return NotificationPreferenceSchema()


# ==================== Change Password (OTP-Verified) ====================


@router.post(
    "/change-password/",
    auth=BearerAuth(),
    response={200: MessageOut, 401: MessageOut, 429: MessageOut},
)
async def change_password(request, payload: ChangePasswordIn):
    """
    Step 1 of password change: Verify current password, then send OTP.
    Returns a message — user must call /change-password/confirm/ next.
    """
    user = request.user

    if not await user.acheck_password(payload.current_password):
        return 401, {"message": "Current password is incorrect."}

    try:
        from .services import create_and_send_otp

        await create_and_send_otp(user.email, "change_password", user=user)
    except ValueError as e:
        return 429, {"message": str(e)}

    return 200, {"message": "OTP sent to your email for password change verification."}


@router.post(
    "/change-password/confirm/",
    auth=BearerAuth(),
    response={200: MessageOut, 401: MessageOut},
)
async def change_password_confirm(request, payload: ChangePasswordConfirmIn):
    """
    Step 2 of password change: Verify OTP and set new password.
    """
    from .services import verify_otp

    user = request.user

    # Ensure the OTP email matches the authenticated user
    if payload.email != user.email:
        return 401, {"message": "Email does not match authenticated user."}

    try:
        await verify_otp(payload.email, payload.otp, "change_password")
    except ValueError as e:
        return 401, {"message": str(e)}

    # Set new password
    user.set_password(payload.new_password)
    await user.asave(update_fields=["password", "updated_at"])

    return 200, {"message": "Password changed successfully."}


# ==================== Forgot Password (OTP-Verified, Unauthenticated) ====================


@router.post(
    "/forgot-password/",
    response={200: MessageOut, 401: MessageOut, 429: MessageOut},
)
async def forgot_password(request, payload: ForgotPasswordIn):
    """
    Step 1 of forgot password: Validate email exists and is active, then send OTP.
    Returns a message — user must call /forgot-password/confirm/ next.

    NOTE: Always returns 200 for valid emails to prevent email enumeration.
    """
    try:
        user = await User.objects.aget(email=payload.email, is_active=True)
    except User.DoesNotExist:
        # Don't reveal whether email exists — return same message
        return 200, {
            "message": "If this email is registered, you will receive a verification code."
        }

    try:
        from .services import create_and_send_otp

        await create_and_send_otp(user.email, "forgot_password", user=user)
    except ValueError as e:
        return 429, {"message": str(e)}

    return 200, {
        "message": "If this email is registered, you will receive a verification code."
    }


@router.post(
    "/forgot-password/confirm/",
    response={200: MessageOut, 401: MessageOut},
)
async def forgot_password_confirm(request, payload: ForgotPasswordConfirmIn):
    """
    Step 2 of forgot password: Verify OTP and set new password.
    Unauthenticated — user proves identity via OTP.
    """
    from .services import verify_otp

    # Verify the OTP
    try:
        await verify_otp(payload.email, payload.otp, "forgot_password")
    except ValueError as e:
        return 401, {"message": str(e)}

    # Look up user and set new password
    try:
        user = await User.objects.aget(email=payload.email, is_active=True)
    except User.DoesNotExist:
        return 401, {"message": "No active account found with this email."}

    user.set_password(payload.new_password)
    await user.asave(update_fields=["password", "updated_at"])

    return 200, {
        "message": "Password reset successfully. You can now log in with your new password."
    }
