# Generated by Django 5.2.12 on 2026-04-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldMortgage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('borrower_name', models.CharField(max_length=255)),
                ('borrower_phone', models.CharField(blank=True, default='', max_length=50)),
                ('borrower_email', models.EmailField(blank=True, default='', max_length=254)),
                ('borrower_address', models.TextField(blank=True, default='')),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('business', 'Business'), ('colleague', 'Colleague'), ('other', 'Other')], default='other', max_length=20)),
                ('collateral', models.JSONField(blank=True, default=dict)),
                ('loan_amount', models.BigIntegerField(default=0)),
                ('current_balance', models.BigIntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=20)),
                ('term_months', models.IntegerField(default=0)),
                ('expected_monthly_payment', models.BigIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_payment_due_date', models.DateField(blank=True, null=True)),
                ('total_received_amount', models.BigIntegerField(default=0)),
                ('total_interest_earned', models.BigIntegerField(default=0)),
                ('received_installments', models.IntegerField(default=0)),
                ('total_installments', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('foreclosed', 'Foreclosed'), ('in_review', 'In Review')], default='active', max_length=20)),
                ('late_payment_penalty_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grace_period_days', models.IntegerField(default=0)),
                ('bank_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Held Mortgage',
                'verbose_name_plural': 'Held Mortgages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeldMortgagePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.BigIntegerField(default=0)),
                ('principal_component', models.BigIntegerField(default=0)),
                ('interest_component', models.BigIntegerField(default=0)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_number', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_mortgage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mortgage.heldmortgage')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Held Mortgage Payment',
                'verbose_name_plural': 'Held Mortgage Payments',
                'ordering': ['payment_number'],
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property', models.JSONField(blank=True, default=dict)),
                ('lender_name', models.CharField(max_length=255)),
                ('loan_amount', models.BigIntegerField(default=0)),
                ('down_payment', models.BigIntegerField(default=0)),
                ('down_payment_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_balance', models.BigIntegerField(default=0)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=20)),
                ('term_months', models.IntegerField(default=0)),
                ('emi_amount', models.BigIntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('paid_installments', models.IntegerField(default=0)),
                ('total_installments', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('in_review', 'In Review')], default='active', max_length=20)),
                ('escrow', models.JSONField(blank=True, default=dict)),
                ('bank_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mortgage',
                'verbose_name_plural': 'Mortgages',
                'ordering': ['-created_at'],
            },
        ),
    ]
